services:
  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
  redis:
    ports:
      - "${REDIS_PORT:-6380}:6379"
  backend:
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./backend:/app
  celery_worker:
    volumes:
      - ./backend:/app
